<a href="https://colab.research.google.com/github/tanishq252/AI-ML-DS-Learning-Series/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Kaggle tutorial to make your linear regression model better](https://www.kaggle.com/jnikhilsai/cross-validation-with-linear-regression)
###in the cancer dataset K-fold cross validation and RFE are being applied

##Importing dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:

dataSet = pd.read_csv('50_Startups.csv')
dataSet.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
x = dataSet.iloc[:,:-1].values
y = dataSet.iloc[:,-1].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

##Encoding categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# shift+tab to see arguments and their importance .... the index '0' is the column which we have to encode
# in categorical format
# as we want last column of the data set to be one hot encoded so we have entered -1
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [-1])], remainder = 'passthrough')
# to update the x value
x = np.array(ct.fit_transform(x))

In [5]:
# here we can see that the state column is being encoded properly
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

##Splitting the dataset

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8,random_state=0)


##Feature Scaling
####It is necessary as we are having multiple variables whose range of values differs from each other

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train) 
x_test = sc.transform(x_test)
print(x_train)

[[-0.81649658  1.73205081 -0.73379939 -0.35006454 -0.78547109  0.1011968 ]
 [-0.81649658 -0.57735027  1.36277029 -0.55530319 -1.48117426  0.02734979]
 [-0.81649658  1.73205081 -0.73379939  0.07935762  0.80133381 -0.55152132]
 [ 1.22474487 -0.57735027 -0.73379939 -0.54638238  1.32505817  0.07011684]
 [-0.81649658  1.73205081 -0.73379939  0.43485371 -0.35598663  0.75148516]
 [-0.81649658  1.73205081 -0.73379939  1.26943143  0.85518519  0.98603118]
 [-0.81649658  1.73205081 -0.73379939  1.04525007  1.28077047  0.4404    ]
 [-0.81649658 -0.57735027  1.36277029 -1.529843    0.02942065 -1.6218751 ]
 [-0.81649658 -0.57735027  1.36277029 -1.53976251 -2.76767264 -1.6372965 ]
 [-0.81649658 -0.57735027  1.36277029 -0.13115188  1.14497701 -0.76949991]
 [-0.81649658 -0.57735027  1.36277029  0.92791613 -0.02992062  0.48303162]
 [-0.81649658  1.73205081 -0.73379939 -0.20932933 -0.2993768  -0.89915412]
 [ 1.22474487 -0.57735027 -0.73379939 -0.17870828  0.2251352  -1.26401642]
 [ 1.22474487 -0.57735027

##Fitting the model

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [9]:
# let us fit the model now 
model.fit(x_train, y_train)

LinearRegression()

##Prediction on test_data

In [11]:
y_pred= model.predict(x_test)

In [12]:
# to compare the prediceted and actual outputs let us concatenate both of em and print so that it is easy to check ;)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [52]:
# here we have a close resemblance between the actual and predicted values :D

In [14]:
# acuuracy on test data
model.score(x_test, y_test)

0.9347068473282423

In [15]:
# so we get training accuracy of around 95%
model.score(x_train, y_train)

0.9501847627493607

#Cancer dataset
#### let us now calculate perimeter_se using diagnosis, radius_mean, smoothness_mean


In [24]:
dataSet = pd.read_csv('data.csv')
dataSet.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [164]:
x = dataSet.iloc[:,1:14].values
# x = dataSet.iloc[:,1:8].values #65% accuracy
# x = dataSet.iloc[:,1:6].values #50% accuracy
# x = dataSet.iloc[:,1:7].values #60% accuracy
# try doing this and u will get a good one
# x = dataSet[['diagnosis', 'radius_mean']]

y = dataSet.iloc[:,14].values

In [165]:
x = np.array(x)
x,y

(array([['M', 17.99, 10.38, ..., 0.07871, 1.095, 0.9053],
        ['M', 20.57, 17.77, ..., 0.056670000000000005, 0.5435, 0.7339],
        ['M', 19.69, 21.25, ..., 0.059989999999999995, 0.7456, 0.7869],
        ...,
        ['M', 16.6, 28.08, ..., 0.056479999999999995, 0.4564, 1.075],
        ['M', 20.6, 29.33, ..., 0.07016, 0.726, 1.595],
        ['B', 7.76, 24.54, ..., 0.058839999999999996, 0.3857,
         1.4280000000000002]], dtype=object),
 array([ 8.59,  3.4 ,  4.58,  3.44,  5.44,  2.22,  3.18,  3.86,  2.41,
         2.04,  2.47,  3.56, 11.07,  2.9 ,  2.06,  2.88,  3.19,  3.85,
         5.87,  2.06,  1.38,  1.91,  3.38,  4.3 ,  5.46,  7.28,  2.11,
         5.63,  3.5 ,  4.66,  5.57,  3.48,  4.  ,  3.53,  2.18,  3.01,
         2.66,  1.17,  8.08,  1.54,  1.57,  1.82,  8.83,  2.43,  1.33,
         4.29,  1.09,  1.9 ,  1.85,  1.74,  2.63,  1.45,  1.52,  4.88,
         2.1 ,  2.18,  4.84,  2.73,  2.6 ,  1.05,  3.31,  2.49,  5.37,
         2.61,  2.93,  2.45,  1.66,  1.83,  1.89,  1.4

##One hot encoding on diagnosis column

In [166]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# shift+tab to see arguments and their importance .... the index '0' is the column which we have to encode
# in categorical format
# as we want first column(diagnosis) of the data set to be one hot encoded so we have entered 0
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
# to update the x value
x = np.array(ct.fit_transform(x))

In [167]:
x

array([[0.0, 1.0, 17.99, ..., 0.07871, 1.095, 0.9053],
       [0.0, 1.0, 20.57, ..., 0.056670000000000005, 0.5435, 0.7339],
       [0.0, 1.0, 19.69, ..., 0.059989999999999995, 0.7456, 0.7869],
       ...,
       [0.0, 1.0, 16.6, ..., 0.056479999999999995, 0.4564, 1.075],
       [0.0, 1.0, 20.6, ..., 0.07016, 0.726, 1.595],
       [1.0, 0.0, 7.76, ..., 0.058839999999999996, 0.3857,
        1.4280000000000002]], dtype=object)

##Splitting the dataset


In [168]:
from sklearn.model_selection import train_test_split
x_Train, x_Test, y_Train, y_Test = train_test_split(x,y,train_size = 0.8)

###Feature Scaling as all variables are not in a plausible range

In [169]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_Train = sc.fit_transform(x_Train) 
x_Test = sc.transform(x_Test)
print(x_Train)

[[ 7.76e-01 -7.76e-01 -6.84e-01 ...  1.50e+00 -4.15e-01  1.34e+00]
 [ 7.76e-01 -7.76e-01 -7.27e-01 ...  6.45e-01 -4.79e-01  9.68e-01]
 [ 7.76e-01 -7.76e-01 -8.05e-01 ...  8.26e-01 -5.62e-01 -4.27e-01]
 ...
 [-1.29e+00  1.29e+00  1.19e+00 ... -1.58e-03  1.58e+00  6.56e-01]
 [ 7.76e-01 -7.76e-01 -3.34e-01 ... -8.82e-01 -7.92e-01 -5.65e-01]
 [ 7.76e-01 -7.76e-01 -1.62e-01 ... -3.18e-01 -7.20e-01  1.90e-01]]


###Fitting the model

In [170]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_Train, y_Train)

LinearRegression()

In [171]:
# training data set
regressor.score(x_Train, y_Train)

0.9635520476830198

In [172]:
# without feature scaling we get around 74% accuracy
# with feature scaling we get around 75% accuracy
# this model was consisting starting 6 columns which was giving 17% accuracy on dataset

###Prediction on test data

In [173]:
y_PRED = regressor.predict(x_Test)

In [174]:
# to compare the prediceted and actual outputs let us concatenate both of em and print so that it is easy to check ;)
np.set_printoptions(precision = 2)
print(np.concatenate((y_PRED.reshape(len(y_PRED),1), y_Test.reshape(len(y_Test),1)),1))

[[ 3.12  3.13]
 [ 0.83  0.77]
 [ 2.11  1.94]
 [ 2.03  2.15]
 [ 3.03  2.86]
 [ 1.65  1.73]
 [ 2.48  2.04]
 [ 4.87  4.78]
 [ 4.48  4.61]
 [ 3.04  3.15]
 [ 2.15  1.96]
 [ 2.22  1.97]
 [ 2.04  2.  ]
 [ 5.68  5.44]
 [ 1.9   1.93]
 [ 1.71  1.87]
 [ 1.65  1.57]
 [ 2.16  2.08]
 [ 2.    2.08]
 [ 2.27  2.11]
 [ 4.82  4.53]
 [ 3.36  3.93]
 [ 1.69  1.67]
 [ 2.46  2.47]
 [ 2.36  2.31]
 [ 1.4   1.37]
 [ 2.53  2.68]
 [ 2.62  2.55]
 [ 3.54  2.55]
 [ 4.1   4.22]
 [ 1.44  1.49]
 [ 2.24  2.28]
 [ 2.73  3.59]
 [ 2.54  2.46]
 [ 1.79  2.29]
 [ 1.83  1.95]
 [ 4.28  4.91]
 [ 1.59  1.77]
 [ 1.44  1.43]
 [ 1.7   1.7 ]
 [ 2.78  2.5 ]
 [ 1.39  1.53]
 [ 2.98  2.64]
 [ 1.48  1.52]
 [ 9.16  8.87]
 [ 1.82  1.96]
 [ 2.72  2.82]
 [ 2.62  2.77]
 [ 4.91  4.41]
 [ 2.06  1.92]
 [ 1.08  1.1 ]
 [ 1.9   2.14]
 [ 2.57  2.75]
 [ 1.61  1.56]
 [ 3.08  3.19]
 [ 3.1   3.18]
 [ 5.    5.12]
 [ 2.46  2.6 ]
 [ 5.2   4.72]
 [ 1.49  1.45]
 [ 1.42  1.52]
 [ 2.85  2.7 ]
 [ 2.38  2.35]
 [ 0.86  1.07]
 [ 4.07  3.6 ]
 [ 1.92  1.78]
 [ 4.54  4

In [175]:
from sklearn.metrics import r2_score

r2_score(y_Test, y_PRED)

0.9780248839198086

In [176]:
regressor.score(x_Test, y_Test)

0.9780248839198086

###Using *RFE*
RFE is Recursive Feature Elimination, or RFE for short, is a feature selection algorithm.

A machine learning dataset for classification or regression is comprised of rows and columns, like an excel spreadsheet. Rows are often referred to as samples and columns are referred to as features, e.g. features of an observation in a problem domain.

Feature selection refers to techniques that select a subset of the most relevant features (columns) for a dataset. Fewer features can allow machine learning algorithms to run more efficiently (less space or time complexity) and be more effective. Some machine learning algorithms can be misled by irrelevant input features, resulting in worse predictive performance.

[RFE detailed explanation](https://machinelearningmastery.com/rfe-feature-selection-in-python/)

In [178]:
from sklearn.feature_selection import RFE

lm = LinearRegression()
lm.fit(x_Train, y_Train)

rfe = RFE(lm, n_features_to_select=10)             
rfe = rfe.fit(x_Train, y_Train)

In [179]:
yPred =  rfe.predict(x_Test)

In [180]:
r2_score(y_Test, yPred)

0.9779578887556146

###K-Fold Cross Validation
k-Fold Cross-Validation
Cross-validation is a resampling procedure used to evaluate machine learning models on a limited data sample.

The procedure has a single parameter called k that refers to the number of groups that a given data sample is to be split into. As such, the procedure is often called k-fold cross-validation. When a specific value for k is chosen, it may be used in place of k in the reference to the model, such as k=10 becoming 10-fold cross-validation.

Cross-validation is primarily used in applied machine learning to estimate the skill of a machine learning model on unseen data. That is, to use a limited sample in order to estimate how the model is expected to perform in general when used to make predictions on data not used during the training of the model.

It is a popular method because it is simple to understand and because it generally results in a less biased or less optimistic estimate of the model skill than other methods, such as a simple train/test split.

[K-Fold Cross Validation ](https://machinelearningmastery.com/k-fold-cross-validation/)

In [182]:

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

# create a KFold object with 5 splits 
folds = KFold(n_splits = 10, shuffle = True, random_state = 100)
scores = cross_val_score(lm, x_Train, y_Train, scoring='r2', cv=folds)
scores  

array([0.97, 0.96, 0.89, 0.96, 0.96, 0.97, 0.98, 0.98, 0.95, 0.96])