<a href="https://colab.research.google.com/github/tanishq252/AI-ML-DS-Learning-Series/blob/main/processing_and_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing data and libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as ply

In [ ]:
# initializing the dataset
dataframe = pd.read_csv('data.csv')
dataframe.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
dataframe.tail()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[5 rows x 33 columns]

In [ ]:
# taking the independent values in x so that y will have dependent values and we can implement what we want over there
x = dataframe.iloc[:,2:].values

In [ ]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 4.601e-01 1.189e-01       nan]
 [2.057e+01 1.777e+01 1.329e+02 ... 2.750e-01 8.902e-02       nan]
 [1.969e+01 2.125e+01 1.300e+02 ... 3.613e-01 8.758e-02       nan]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 2.218e-01 7.820e-02       nan]
 [2.060e+01 2.933e+01 1.401e+02 ... 4.087e-01 1.240e-01       nan]
 [7.760e+00 2.454e+01 4.792e+01 ... 2.871e-01 7.039e-02       nan]]


In [ ]:
# the y values are the values to be predicted most probably
y = dataframe.iloc[:,1].values
y

# Nan values handling

In [ ]:
from sklearn.impute import SimpleImputer
imputer  = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imputer.fit(x[:, 2:])  #fits data as per we wanted and as per our strategy

SimpleImputer()

In [ ]:
x = imputer.transform(x[:, 2:])  #updates x along with the changes made in previous commands


In [ ]:
print(x)
# reults in no nan values as such present

[[1.228e+02 1.001e+03 1.184e-01 ... 2.654e-01 4.601e-01 1.189e-01]
 [1.329e+02 1.326e+03 8.474e-02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.300e+02 1.203e+03 1.096e-01 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.083e+02 8.581e+02 8.455e-02 ... 1.418e-01 2.218e-01 7.820e-02]
 [1.401e+02 1.265e+03 1.178e-01 ... 2.650e-01 4.087e-01 1.240e-01]
 [4.792e+01 1.810e+02 5.263e-02 ... 0.000e+00 2.871e-01 7.039e-02]]


# label encoding and one hot encoding

In [ ]:
# in this data set it is not required but onehotencoding is important when we build multi class classifiers 
# just the syntax is given over here 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# shift+tab to see arguments and their importance .... the index '0' is the column which we have to encode
# in categorical format
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
# to update the x value
x = np.array(ct.fit_transform(x))

In [ ]:
# it  is easy to change data in categorical representation as we have inbuilt libraries

In [ ]:
# label encoding used to give labels to data NOTE : try label encoding once on data and one hot encoding later
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
y = labelEncoder.fit_transform(y)

In [ ]:
print(y)
# as we had only 2 outputs accordingly data has been encoded

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

# Splitting data in training and testing data sets

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8,random_state=0)

In [ ]:
x_test

array([[8.864e+01, 5.567e+02, 1.106e-01, ..., 2.051e-01, 3.585e-01,
        1.109e-01],
       [8.410e+01, 5.379e+02, 8.791e-02, ..., 6.005e-02, 2.444e-01,
        6.788e-02],
       [8.959e+01, 6.065e+02, 7.966e-02, ..., 8.216e-02, 2.136e-01,
        6.710e-02],
       ...,
       [1.338e+02, 1.250e+03, 1.133e-01, ..., 2.173e-01, 3.032e-01,
        8.075e-02],
       [1.208e+02, 1.052e+03, 1.068e-01, ..., 1.510e-01, 3.074e-01,
        7.863e-02],
       [9.873e+01, 6.894e+02, 9.883e-02, ..., 1.018e-01, 2.177e-01,
        8.549e-02]])

# Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train) # asnwer has to be found from given dataset and given dataset has to be transformed accordingly
x_test = sc.transform(x_test) # we dont want to perform feature scaling but just transform our test data set

In [ ]:
  print(x_train)

[[-1.12855021 -0.95876358  0.3109837  ... -0.75798367 -0.01614761
  -0.38503402]
 [-0.94820146 -0.82152548 -0.60963604 ... -0.60687023  0.09669004
  -0.38615797]
 [ 0.51394098  0.40858627 -0.10616078 ... -0.02371948 -0.20050207
  -0.75144254]
 ...
 [-1.31754581 -1.04876494  0.32549308 ... -0.97974953 -0.71542314
  -0.11978123]
 [-1.28007609 -1.02221174 -1.95247854 ... -1.75401433 -1.58157125
  -1.00601779]
 [-0.71226578 -0.69966029 -0.27592045 ... -0.27460457 -1.25895095
   0.21515662]]


In [ ]:
print(x_test)

[[-0.13086754 -0.27145506  1.02919769 ...  1.3893291   1.08203284
   1.54029664]
 [-0.31780437 -0.32400244 -0.61689072 ... -0.83369364 -0.73131577
  -0.87732522]
 [-0.09175081 -0.13226041 -1.21540238 ... -0.49483785 -1.22080864
  -0.92115937]
 ...
 [ 1.7286186   1.66636924  1.22507423 ...  1.57630515  0.20317063
  -0.15406178]
 [ 1.19333694  1.11294474  0.75351959 ...  0.56019755  0.26991966
  -0.27320074]
 [ 0.28459338  0.09945116  0.17532106 ... -0.19383705 -1.15564888
   0.11231497]]
